
version: "3.9"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./aws/rds:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${DB_USER}", "--password=${DB_PASS}"]

  node:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/AWS-FCJ-Management
